/**
 * Static portfolio holdings with prices, derived from backend/portfolio.py
 * and backend/data/stock_prices.csv. Provides instant first paint while
 * the Render backend wakes up from cold start.
 *
 * Shape must match the /api/portfolio response holdings array.
 */

export const FALLBACK_GENERATED_AT = "2026-03-29T00:00:00Z";

const fallbackHoldings = [
  {
    symbol: "AAPL",
    name: "Apple",
    shares: 42,
    avgCost: 184.1,
    price: 214.65,
    currency: "USD",
    dayChange: 1.17,
    dayChangePct: 0.55,
    thesis: "Consumer ecosystem moat plus services margin expansion.",
    catalyst: "WWDC AI rollout and buyback support.",
    risk: "iPhone replacement cycle slows if consumer demand softens.",
    notes: ["Large-cap core", "Low turnover", "Good tax lot cushion"],
  },
  {
    symbol: "MSFT",
    name: "Microsoft",
    shares: 18,
    avgCost: 376.84,
    price: 428.9,
    currency: "USD",
    dayChange: 2.78,
    dayChangePct: 0.65,
    thesis: "Cloud cash flow funds AI capex without stressing quality.",
    catalyst: "Azure AI monetization and Copilot attach rate.",
    risk: "Valuation is rich if enterprise AI spend pauses.",
    notes: ["AI platform exposure", "Core compounder", "High quality"],
  },
  {
    symbol: "JPM",
    name: "JPMorgan",
    shares: 35,
    avgCost: 171.42,
    price: 198.34,
    currency: "USD",
    dayChange: 1.29,
    dayChangePct: 0.65,
    thesis: "Best-in-class bank franchise with diversified earnings.",
    catalyst: "NII resilience and capital return.",
    risk: "Credit costs rise if macro deteriorates.",
    notes: ["Financial ballast", "Dividend support", "Lower beta"],
  },
  {
    symbol: "NVDA",
    name: "NVIDIA",
    shares: 16,
    avgCost: 92.33,
    price: 118.77,
    currency: "USD",
    dayChange: 1.85,
    dayChangePct: 1.58,
    thesis: "AI compute demand remains supply constrained.",
    catalyst: "Blackwell ramp and inference demand.",
    risk: "Position can become oversized after sharp rallies.",
    notes: ["Higher volatility", "Strong momentum", "Trim candidate"],
  },
  {
    symbol: "AMZN",
    name: "Amazon",
    shares: 14,
    avgCost: 163.25,
    price: 179.43,
    currency: "USD",
    dayChange: -0.65,
    dayChangePct: -0.36,
    thesis: "Retail margins and AWS cash flow support long-duration growth.",
    catalyst: "AWS acceleration and advertising expansion.",
    risk: "Margin upside fades if consumer spending slows.",
    notes: ["Consumer plus cloud", "Secular growth", "Execution heavy"],
  },
  {
    symbol: "GOOGL",
    name: "Alphabet",
    shares: 20,
    avgCost: 145.8,
    price: 164.52,
    currency: "USD",
    dayChange: 1.41,
    dayChangePct: 0.86,
    thesis: "Search cash flows fund AI investment without leverage stress.",
    catalyst: "AI product adoption and cloud operating leverage.",
    risk: "AI competition pressures search economics.",
    notes: ["Cash-rich", "Ad cyclical", "AI optionality"],
  },
  {
    symbol: "LLY",
    name: "Eli Lilly",
    shares: 8,
    avgCost: 712.4,
    price: 836.25,
    currency: "USD",
    dayChange: 4.11,
    dayChangePct: 0.49,
    thesis: "Obesity and diabetes franchise drives multi-year earnings growth.",
    catalyst: "Manufacturing scale and expanded indications.",
    risk: "High expectations leave little room for execution misses.",
    notes: ["Healthcare growth", "Premium multiple", "Lower correlation"],
  },
  {
    symbol: "XOM",
    name: "Exxon Mobil",
    shares: 26,
    avgCost: 101.7,
    price: 112.68,
    currency: "USD",
    dayChange: -0.76,
    dayChangePct: -0.67,
    thesis: "Cash generation and capital discipline support shareholder returns.",
    catalyst: "Production growth and oil price support.",
    risk: "Commodity exposure can drag if crude weakens.",
    notes: ["Energy hedge", "Dividend support", "Cyclical"],
  },
];

export default fallbackHoldings;
